
version: '3.9'  # Compatible con Docker 20.10+

services:
  unbound:
    container_name: unbound
    build:
      context: .
      dockerfile: Dockerfile
    image: dagorret/unbound:latest
    ports:
      - "5335:53/udp"  # DNS UDP externo
      - "5335:53/tcp"  # DNS TCP externo
    volumes:
      - ./etc:/etc/unbound              # Configuración editable desde el host
      - unbound-control:/var/unbound-control  # Archivos de control remoto (solo contenedor)
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "dig +short github.com @127.0.0.1 -p 53"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      - TZ=America/Argentina/Cordoba
    networks:
      default:
        aliases:
          - dns.local  # Para resolución interna en la red Docker

volumes:
  unbound-control:

networks:
  default:
    driver: bridge  # Red aislada por defecto
